/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lanny_com_so_JniUtils */

#ifndef _Included_lanny_com_so_JniUtils
#define _Included_lanny_com_so_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lanny_com_so_JniUtils
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_lanny_com_so_JniUtils_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
